name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      template: terminal
      filename: metrics.terminal.svg
      token: ${{ secrets.METRICS_TOKEN }}
      base: header, metadata
      - name: Full-year calendar
        uses: 0xStabby/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: 📙 Terminal template - Example
        uses: 0xStabby/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          output_action: none
          delay: 120
          user: 0xStabby
          plugins_errors_fatal: yes
